required = ["github.com/dominikschulz/github-releases", "github.com/muesli/goprogressbar"]

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.1"

[[constraint]]
  name = "github.com/justwatchcom/gopass"
  version = "1.6.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/dominikschulz/github-releases"
  branch = "master"

[[constraint]]
  name = "github.com/muesli/goprogressbar"
  branch = "master"
