required = ["github.com/dominikschulz/github-releases", "github.com/muesli/goprogressbar"]

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.12.0-beta1"

[[constraint]]
  name = "github.com/dominikschulz/github-releases"
  branch = "master"

[[constraint]]
  name = "github.com/muesli/goprogressbar"
  branch = "master"

[[constraint]]
  name = "github.com/gopasspw/gopass"
  version = "1.8.1"

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "956e03eb6ddaa1e736001b4aaa057fe5a33ef57f"
